### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by zahiid** [OpenDofus/wiki#1]
Hi , first hank you for this great tutorial . I've tried to use the dev mode , but unfortunately the client can't connect to the server (it blocks at 50%) . Any idea pls ? thank you :) !

**Comment by LuaxY** [comment]
Hi, please create empty file "debug.txt" in dofus folder and use log system (F11) when client is stuck at 50%. In HTML report you probably have the reason. Post the error or the report here if you want more help.

More informations here: https://github.com/LuaxY/OpenDofus/wiki/Syst%C3%A8me-de-log

**Comment by zahiid** [comment]
Here is the debug file , http://puu.sh/lPeNb/75cae04d02.html , ty for being too fast :D !

**Comment by LuaxY** [comment]
If you have config-custom.xml, try to set this following value to false :

```xml
<entry key="dev.auto.display.controler">false</entry>
<entry key="dev.auto.display.eventUtil">false</entry>
<entry key="dev.auto.display.luaUtil">false</entry>
```

-- 

Have you try to modify a protected dofus file (or the client directly) ?

```
[16:10:06:046] [ServerControlFrame] Bytecode len: 5927, hash: 59902655bf3fe033444a7b339eb6b5be
[16:10:06:064] [ServerControlFrame] Signature incorrecte
```

You have incorrect signature error. This happen when you try to load protected file (file who begin by "AKFS" magic header) or when your client receive custom made RawDataMessage, but I don't think is the case right here.

**Comment by zahiid** [comment]
Ah , thank you for deleting it , i've never tried to change the client (but i think that another program did it "Netfu bot") , thank you for response , for "show logs button" , it seems normal , there is no error :)

**Comment by zahiid** [comment]
But the uploader re-download for me the original client every time i want to get connected on the original client .

**Comment by Skinz3** [comment]
Dont use the official client uplauncher, you only need to run Dofus.exe in your app directory.
