### ISSUE TITLE
Activer un Module

### ISSUE THREAD

**Issue by pop123123123** [OpenDofus/wiki#2]
Bonjour,
très bon wiki, mais j'ai du mal à tester des modules :
dofus me propose le module que je tente d'activer, je clique sur la checkbox et il me déconnecte afin de l'activer.
Ensuite, plus rien, aucun module n'est présent dans la liste (même officiel).
Un petit coup de pouce ? merci :)

**Comment by LuaxY** [comment]
Regarde dans le rapport de log s'il n'y a pas une erreur lié aux modules.
Le pages du wiki concernants les modules seront poursuivis une fois la refonte des modules terminé du côté d'Ankama.

**Comment by pop123123123** [comment]
J'ai testé avec "ankama exemple", et voilà ce que ça donne :

[14:31:00:595] [UiModuleManager] hash file://D:/Programs/Dofus Beta/app/ui/Ankama_Exemple/AnkamaExemple.swf
[14:31:00:596] [UiModuleManager] Hash incorrect pour le module Ankama_Exemple
[14:31:00:597] [UiModuleManager] Le module Ankama_Exemple est désactivé

Je connais pas trop flash, d'où peut venir ce problème de hash ?

**Comment by LuaxY** [comment]
Oui, c'est un module custom, donc il est désactiver de base.
Ya aucun autre logs après son activation depuis le Marketplace ?

**Comment by pop123123123** [comment]
Si,
[14:31:02:232] [UiModuleManager] Impossible d'instancier la classe principale du module Ankama_Exemple

**Comment by LuaxY** [comment]
Quel version de Dofus ?

**Comment by pop123123123** [comment]
Actuelle beta, donc 2.35.0

**Comment by LuaxY** [comment]
C'est normale alors, il faut attendre la refonte des modules. Ou alors si t'es très motivé tu regarde le code source des modules officiel pour t'en inspiré.

**Comment by pop123123123** [comment]
La dernière release compatible était quand ?

**Comment by LuaxY** [comment]
La dernière version de DofusUI est 2.18

**Comment by pop123123123** [comment]
Merci beaucoup ! (et désolé pour la réponse tardive)

**Comment by ngouy** [comment]
Est ce que tout ce chmil blick est toujours d'actualitée ? je n'arrive pas a trouver ou ajouter un module dans les paramètres du jeu

**Comment by LuaxY** [comment]
La doc est incomplète et pas à jour, je doute que cela fonctionne en l'état, il y à surement un travail de recherche et développement en amont à faire avant de pouvoir développer des modules rapidement.

**Comment by ngouy** [comment]
Mais l'interface pour ajouter un module est elle toujours dispo sur le jeu ? Je ne la trouve pas ..
